-- MySQL Script generated by MySQL Workbench
-- Wed Aug  5 21:21:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ArtGalleryManagementDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ArtGalleryManagementDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ArtGalleryManagementDB` DEFAULT CHARACTER SET utf8;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `ArtGalleryManagementDB` ;

-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`User` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`User` (
  `userid` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`accountType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`accountType` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`accountType` (
  `description` VARCHAR(250) NOT NULL,
  `accttypeId` INT NOT NULL,
  PRIMARY KEY (`accttypeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`Account` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`Account` (
  `acctId` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `acctType` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`acctId`),
  INDEX `acctType_idx` (`acctType` ASC) VISIBLE,
  INDEX `userId_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `acctType`
    FOREIGN KEY (`acctType`)
    REFERENCES `ArtGalleryManagementDB`.`accountType` (`accttypeId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `userId`
    FOREIGN KEY (`userId`)
    REFERENCES `ArtGalleryManagementDB`.`User` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`gallery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`gallery` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`gallery` (
  `galleryId` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `manager` VARCHAR(45) NULL,
  PRIMARY KEY (`galleryId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`manage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`manage` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`manage` (
  `managerid` INT NOT NULL,
  `user` INT NOT NULL,
  `galleryId` INT NOT NULL,
  PRIMARY KEY (`managerid`),
  INDEX `userId_idx` (`user` ASC) VISIBLE,
  INDEX `galleryId_idx` (`galleryId` ASC) VISIBLE,
  CONSTRAINT `user`
    FOREIGN KEY (`user`)
    REFERENCES `ArtGalleryManagementDB`.`User` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `gallery_manage`
    FOREIGN KEY (`galleryId`)
    REFERENCES `ArtGalleryManagementDB`.`gallery` (`galleryId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`paymentType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`paymentType` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`paymentType` (
  `typeId` INT NOT NULL,
  `country` VARCHAR(45) NULL,
  `zipcode` INT NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  PRIMARY KEY (`typeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`billingInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`billingInfo` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`billingInfo` (
  `billingId` INT NOT NULL,
  `paymentType` INT NOT NULL,
  `amount` INT NULL,
  `user` INT NOT NULL,
  PRIMARY KEY (`billingId`),
  INDEX `userId_idx` (`user` ASC) VISIBLE,
  INDEX `paymentType_idx` (`paymentType` ASC) VISIBLE,
  CONSTRAINT `paymentType`
    FOREIGN KEY (`paymentType`)
    REFERENCES `ArtGalleryManagementDB`.`paymentType` (`typeId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `userBill`
    FOREIGN KEY (`user`)
    REFERENCES `ArtGalleryManagementDB`.`User` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`creditCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`creditCard` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`creditCard` (
  `cardNumber` INT NOT NULL,
  `Expiration` DATETIME NULL,
  `cvv` INT NULL,
  `paymentType` INT NULL,
  PRIMARY KEY (`cardNumber`),
  INDEX `paymentType_idx` (`paymentType` ASC) VISIBLE,
  CONSTRAINT `paymentTypeid`
    FOREIGN KEY (`paymentType`)
    REFERENCES `ArtGalleryManagementDB`.`paymentType` (`typeId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`bankAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`bankAccount` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`bankAccount` (
  `accountNumber` INT NOT NULL,
  `paymentType` INT NOT NULL,
  `bank` VARCHAR(45) NULL,
  `routingNumber` INT NULL,
  PRIMARY KEY (`accountNumber`),
  INDEX `paymentType_idx` (`paymentType` ASC) VISIBLE,
  CONSTRAINT `paymentTypeid_bank`
    FOREIGN KEY (`paymentType`)
    REFERENCES `ArtGalleryManagementDB`.`paymentType` (`typeId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`feature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`feature` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`feature` (
  `featureId` INT NOT NULL,
  `permission` VARCHAR(250) NOT NULL,
  `tables` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`featureId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`accountFeatures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`accountFeatures` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`accountFeatures` (
  `acctfeatureId` INT NOT NULL,
  `feature` INT NOT NULL,
  `accountType` INT NOT NULL,
  PRIMARY KEY (`acctfeatureId`),
  INDEX `accttypeId_idx` (`accountType` ASC) VISIBLE,
  INDEX `feature_idx` (`feature` ASC) VISIBLE,
  CONSTRAINT `accttypeId`
    FOREIGN KEY (`accountType`)
    REFERENCES `ArtGalleryManagementDB`.`accountType` (`accttypeId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `feature`
    FOREIGN KEY (`feature`)
    REFERENCES `ArtGalleryManagementDB`.`feature` (`featureId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`exhibit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`exhibit` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`exhibit` (
  `exhibitId` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `dateTo` DATETIME NULL,
  `galleryId` INT NOT NULL,
  PRIMARY KEY (`exhibitId`),
  INDEX `galleryId_idx` (`galleryId` ASC) VISIBLE,
  CONSTRAINT `gallery_exhibit`
    FOREIGN KEY (`galleryId`)
    REFERENCES `ArtGalleryManagementDB`.`gallery` (`galleryId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`collection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`collection` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`collection` (
  `collectionId` INT NOT NULL,
  `workCount` INT NULL,
  `galleryId` INT NOT NULL,
  PRIMARY KEY (`collectionId`),
  INDEX `galleryId_idx` (`galleryId` ASC) VISIBLE,
  CONSTRAINT `galleryId`
    FOREIGN KEY (`galleryId`)
    REFERENCES `ArtGalleryManagementDB`.`gallery` (`galleryId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`owner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`owner` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`owner` (
  `name` VARCHAR(250) NOT NULL,
  `ownerId` INT NOT NULL,
  PRIMARY KEY (`ownerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`artwork`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`artwork` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`artwork` (
  `artworkId` INT NOT NULL,
  `price` FLOAT NULL,
  `title` VARCHAR(45) NULL,
  `exhibitId` INT NULL,
  `collectionId` INT NULL,
  `artworkOwnerId` INT NULL,
  PRIMARY KEY (`artworkId`),
  INDEX `exhibitId_idx` (`exhibitId` ASC) VISIBLE,
  INDEX `collectionId_idx` (`collectionId` ASC) VISIBLE,
  INDEX `ownerId_idx` (`artworkOwnerId` ASC) VISIBLE,
  CONSTRAINT `exhibitId`
    FOREIGN KEY (`exhibitId`)
    REFERENCES `ArtGalleryManagementDB`.`exhibit` (`exhibitId`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `collectionId`
    FOREIGN KEY (`collectionId`)
    REFERENCES `ArtGalleryManagementDB`.`collection` (`collectionId`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `artworkOwnerId`
    FOREIGN KEY (`artworkOwnerId`)
    REFERENCES `ArtGalleryManagementDB`.`owner` (`ownerId`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`view` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`view` (
  `userId` INT NOT NULL,
  `artwork` INT NOT NULL,
  `viewId` INT NOT NULL,
  PRIMARY KEY (`viewId`),
  INDEX `userId_idx` (`userId` ASC) VISIBLE,
  INDEX `artword_idx` (`artwork` ASC) VISIBLE,
  CONSTRAINT `userId_view`
    FOREIGN KEY (`userId`)
    REFERENCES `ArtGalleryManagementDB`.`User` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `artwork_view`
    FOREIGN KEY (`artwork`)
    REFERENCES `ArtGalleryManagementDB`.`artwork` (`artworkId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`buy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`buy` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`buy` (
  `userId` INT NOT NULL,
  `artwork` INT NOT NULL,
  `offer` FLOAT NOT NULL,
  `date` DATETIME NULL,
  `purchaseId` INT NOT NULL,
  PRIMARY KEY (`purchaseId`),
  INDEX `artworkId_idx` (`artwork` ASC) VISIBLE,
  CONSTRAINT `artwork_buy`
    FOREIGN KEY (`artwork`)
    REFERENCES `ArtGalleryManagementDB`.`artwork` (`artworkId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `userId_buy`
    FOREIGN KEY (`userId`)
    REFERENCES `ArtGalleryManagementDB`.`User` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`address` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`address` (
  `country` VARCHAR(45) NOT NULL,
  `addressId` INT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `streetNumber` INT NOT NULL,
  `streetName` VARCHAR(45) NULL,
  `galleryAddressId` INT NULL,
  PRIMARY KEY (`addressId`),
  INDEX `galleryId_idx` (`galleryAddressId` ASC) VISIBLE,
  CONSTRAINT `galleryAddressId`
    FOREIGN KEY (`galleryAddressId`)
    REFERENCES `ArtGalleryManagementDB`.`gallery` (`galleryId`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`manager` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`manager` (
  `managerId` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `galleryExhibitId` INT NOT NULL,
  PRIMARY KEY (`managerId`),
  INDEX `galleryId_idx` (`galleryExhibitId` ASC) VISIBLE,
  CONSTRAINT `galleryExhibitId`
    FOREIGN KEY (`galleryExhibitId`)
    REFERENCES `ArtGalleryManagementDB`.`gallery` (`galleryId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`theme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`theme` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`theme` (
  `themeId` INT NOT NULL,
  `description` VARCHAR(250) NULL,
  `curratorName` VARCHAR(45) NULL,
  `exhibitId` INT NOT NULL,
  PRIMARY KEY (`themeId`),
  INDEX `exhibit_idx` (`exhibitId` ASC) VISIBLE,
  CONSTRAINT `exhibit`
    FOREIGN KEY (`exhibitId`)
    REFERENCES `ArtGalleryManagementDB`.`exhibit` (`exhibitId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`medium`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`medium` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`medium` (
  `mediumId` INT NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`mediumId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`artMedium`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`artMedium` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`artMedium` (
  `artwork` INT NOT NULL,
  `medium` INT NOT NULL,
  `artMediumId` INT NOT NULL,
  PRIMARY KEY (`artMediumId`),
  INDEX `mediumId_idx` (`medium` ASC) VISIBLE,
  CONSTRAINT `artwork_artMedium`
    FOREIGN KEY (`artwork`)
    REFERENCES `ArtGalleryManagementDB`.`artwork` (`artworkId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `mediumId`
    FOREIGN KEY (`medium`)
    REFERENCES `ArtGalleryManagementDB`.`medium` (`mediumId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`style`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`style` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`style` (
  `styleId` INT NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`styleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`artStyle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`artStyle` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`artStyle` (
  `style` INT NOT NULL,
  `artwork` INT NOT NULL,
  `artStyleId` INT NOT NULL,
  PRIMARY KEY (`artStyleId`),
  INDEX `artworkId_idx` (`artwork` ASC) VISIBLE,
  CONSTRAINT `artwork_artstyle`
    FOREIGN KEY (`artwork`)
    REFERENCES `ArtGalleryManagementDB`.`artwork` (`artworkId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `styleId`
    FOREIGN KEY (`style`)
    REFERENCES `ArtGalleryManagementDB`.`style` (`styleId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`artPhoto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`artPhoto` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`artPhoto` (
  `photographerName` VARCHAR(45) NOT NULL,
  `photoId` INT NOT NULL,
  `artworkId` INT NOT NULL,
  PRIMARY KEY (`photoId`),
  INDEX `artworkId_idx` (`artworkId` ASC) VISIBLE,
  CONSTRAINT `artwork_artPhoto`
    FOREIGN KEY (`artworkId`)
    REFERENCES `ArtGalleryManagementDB`.`artwork` (`artworkId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`CDN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`CDN` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`CDN` (
  `cdnId` INT NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`cdnId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`imageHosetd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`imageHosetd` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`imageHosetd` (
  `artPhoto` INT NOT NULL,
  `CDN` INT NOT NULL,
  `imageHostedId` INT NOT NULL,
  PRIMARY KEY (`imageHostedId`),
  INDEX `cdnID_idx` (`CDN` ASC) VISIBLE,
  CONSTRAINT `CDN_Image`
    FOREIGN KEY (`CDN`)
    REFERENCES `ArtGalleryManagementDB`.`CDN` (`cdnId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `artPhotoId`
    FOREIGN KEY (`artPhoto`)
    REFERENCES `ArtGalleryManagementDB`.`artPhoto` (`photoId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`artManager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`artManager` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`artManager` (
  `artManagerId` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `artist` INT NOT NULL,
  PRIMARY KEY (`artManagerId`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`artist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`artist` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`artist` (
  `artistId` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `DOB` DATETIME NULL,
  `artManager` INT NULL,
  PRIMARY KEY (`artistId`),
  INDEX `artManagerId_idx` (`artManager` ASC) VISIBLE,
  CONSTRAINT `artManagerId`
    FOREIGN KEY (`artManager`)
    REFERENCES `ArtGalleryManagementDB`.`artManager` (`artManagerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`ownerBankInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`ownerBankInfo` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`ownerBankInfo` (
  `owner` INT NOT NULL,
  `bankAccountId` INT NOT NULL,
  `ownerBankInfoId` INT NOT NULL,
  PRIMARY KEY (`ownerBankInfoId`),
  INDEX `bankAccountId_idx` (`bankAccountId` ASC) VISIBLE,
  CONSTRAINT `ownerId`
    FOREIGN KEY (`owner`)
    REFERENCES `ArtGalleryManagementDB`.`owner` (`ownerId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `bankAccountId`
    FOREIGN KEY (`bankAccountId`)
    REFERENCES `ArtGalleryManagementDB`.`bankAccount` (`accountNumber`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`profile` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`profile` (
  `profileId` INT NOT NULL,
  `artist` INT NOT NULL,
  `introduction` VARCHAR(250) NULL,
  PRIMARY KEY (`profileId`),
  INDEX `artistId_idx` (`artist` ASC) VISIBLE,
  CONSTRAINT `artist_profile`
    FOREIGN KEY (`artist`)
    REFERENCES `ArtGalleryManagementDB`.`artist` (`artistId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`artistPic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`artistPic` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`artistPic` (
  `artistPicId` INT NOT NULL,
  `profile` INT NOT NULL,
  `dateAdded` DATETIME NULL,
  `CDN` INT NOT NULL,
  PRIMARY KEY (`artistPicId`),
  INDEX `profile_idx` (`profile` ASC) VISIBLE,
  INDEX `CDNID_idx` (`CDN` ASC) VISIBLE,
  CONSTRAINT `profile`
    FOREIGN KEY (`profile`)
    REFERENCES `ArtGalleryManagementDB`.`profile` (`profileId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `CDN_artistPic`
    FOREIGN KEY (`CDN`)
    REFERENCES `ArtGalleryManagementDB`.`CDN` (`cdnId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`school`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`school` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`school` (
  `schoolId` INT NOT NULL,
  `schoolName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`schoolId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`educated`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`educated` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`educated` (
  `artist` INT NOT NULL,
  `artInstitute` INT NOT NULL,
  `yearofGraduation` INT NULL,
  `educatedId` INT NOT NULL,
  PRIMARY KEY (`educatedId`),
  INDEX `artInstituteId_idx` (`artInstitute` ASC) VISIBLE,
  CONSTRAINT `artist_educated`
    FOREIGN KEY (`artist`)
    REFERENCES `ArtGalleryManagementDB`.`artist` (`artistId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `artInstituteId`
    FOREIGN KEY (`artInstitute`)
    REFERENCES `ArtGalleryManagementDB`.`school` (`schoolId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`degree`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`degree` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`degree` (
  `degreeId` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`degreeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`degreeRecieved`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`degreeRecieved` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`degreeRecieved` (
  `degree` INT NULL,
  `artist` INT NULL,
  `degreeRecievedId` INT NOT NULL,
  PRIMARY KEY (`degreeRecievedId`),
  INDEX `artistId_idx` (`artist` ASC) VISIBLE,
  CONSTRAINT `degreeID`
    FOREIGN KEY (`degree`)
    REFERENCES `ArtGalleryManagementDB`.`degree` (`degreeId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `artist_degree`
    FOREIGN KEY (`artist`)
    REFERENCES `ArtGalleryManagementDB`.`artist` (`artistId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`session` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`session` (
  `sessionId` INT NOT NULL,
  `userSessionId` INT NOT NULL,
  `expires` DATETIME NOT NULL,
  PRIMARY KEY (`sessionId`),
  INDEX `userId_idx` (`userSessionId` ASC) VISIBLE,
  CONSTRAINT `userSessionId`
    FOREIGN KEY (`userSessionId`)
    REFERENCES `ArtGalleryManagementDB`.`User` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`artManage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`artManage` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`artManage` (
  `artManageId` INT NOT NULL,
  `artWork` INT NOT NULL,
  `user` INT NOT NULL,
  PRIMARY KEY (`artManageId`),
  INDEX `artworkId_idx` (`artWork` ASC) VISIBLE,
  CONSTRAINT `artworkManageId`
    FOREIGN KEY (`artWork`)
    REFERENCES `ArtGalleryManagementDB`.`artwork` (`artworkId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `userManageId`
    FOREIGN KEY (`user`)
    REFERENCES `ArtGalleryManagementDB`.`User` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArtGalleryManagementDB`.`galleryView`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArtGalleryManagementDB`.`galleryView` ;

CREATE TABLE IF NOT EXISTS `ArtGalleryManagementDB`.`galleryView` (
  `user` INT NULL,
  `galleryViewId` INT NOT NULL,
  `gallery` INT NULL,
  PRIMARY KEY (`galleryViewId`),
  INDEX `galleryId_idx` (`gallery` ASC) VISIBLE,
  INDEX `userId_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `gallViewId`
    FOREIGN KEY (`gallery`)
    REFERENCES `ArtGalleryManagementDB`.`gallery` (`galleryId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `userIViewd`
    FOREIGN KEY (`user`)
    REFERENCES `ArtGalleryManagementDB`.`User` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
